<?php
/**
 * Info Page Template
 *
 * @category   Zend
 * @package    Zend_$package
 * @subpackage $subpackage
 * @copyright  Copyright (c) 2018 ecommistry (http://www.ecommistry.com)
 * @license    http://framework.zend.com/license   BSD License
 * @version    Release: 1.0
 * @link       http://framework.zend.com/package/PackageName
 * @since      Class available since Release 1.0
 */

/** @var \Training\SimpleGreeter\Block\Info $block */
?>
<div class="info-wrapper">
    <p class="datetime">Datetime: <?php echo $block->getDatetime() ?></p>
    <p class="store-code">Magento Store
        Code: <?php echo $block->getStoreCode() ?></p>
    <p class="locale">Magento Locale: <?php echo $block->getLocale() ?></p>
    <p class="directory">Magento Base
        Directory: <?php echo $block->getBaseDirectory() ?></p>
</div>

