<?php
/**
 * Blog Page Template
 *
 * Template to display all blog posts.
 *
 * @category   Zend
 * @package    Zend_Ecommistry
 * @subpackage Blog
 * @copyright  Copyright (c) 2018 ecommistry (http://www.ecommistry.com)
 * @license    http://framework.zend.com/license   BSD License
 * @version    Release: 1.0
 * @link       http://framework.zend.com/package/PackageName
 * @since      Class available since Release 1.0
 */

namespace Ecommistry\Blog\view\frontend\templates;

/** @var \Ecommistry\Blog\Block\Blog $block */
/** @var \Ecommistry\Blog\Model\Blog $post */
$collection = $block->getPosts();
?>
<div class="blog">
    <h1>Ecommistry Blog</h1>
    <p><a href="/blog/index/create">Add New Post</a></p>
    <div class="blog-posts">
        <?php foreach ($collection as $post) : ?>
            <div class="blog-post" id="<?php echo $post->getId(); ?>">
                <h3 class="post-title"><a
                            href="/blog/index/edit?id=<?php echo $post->getId(); ?>"
                    ><?php echo $post->getTitle(); ?>
                    </a>
                </h3>
                <p class="post-date">
                    <?php echo $post->getCreationTime(); ?>
                    <a href="/blog/index/delete?id=<?php echo $post->getId(); ?>">delete?</a>
                </p>
                <p class="post-content"><?php echo $post->getContent(); ?></p>
            </div>
        <?php endforeach; ?>
    </div>
</div>