<?php
/**
 * Blog Page Template
 *
 * Template to display all blog posts.
 *
 * @category   Ecommistry
 * @package    Ecommistry_Blog
 * @copyright  Copyright (c) 2018 ecommistry (http://www.ecommistry.com)
 * @license    http://framework.zend.com/license   BSD License
 * @version    Release: 1.0
 * @link       http://framework.zend.com/package/PackageName
 * @since      Class available since Release 1.0
 */

namespace Ecommistry\Blog\view\frontend\templates;

/** @var \Ecommistry\Blog\Block\Blog $block */
/** @var \Ecommistry\Blog\Api\Data\BlogInterface $post */

use Ecommistry\Blog\Setup\InstallSchema;

$collection = $block->getPosts();
?>
<div class="blog">
    <h1>Ecommistry Blog</h1>
    <p><a href="<?php echo $block->getUrl('blog/index/create'); ?>"
        >Add New Post</a></p>
    <div class="blog-posts">
        <?php if (!$collection) : ?>
            <p>No Blog Posts to Show</p>
        <?php else : ?>
            <?php foreach ($collection as $post) : ?>
                <div class="blog-post" id="<?php echo $post->getId(); ?>">
                    <h3 class="post-title"><a
                                href="<?php echo $block->getUrl(
                                    'blog/index/edit',
                                    [InstallSchema::ID_FIELD_NAME => $post->getId()]
                                ); ?>"
                        ><?php echo $post->getTitle(); ?>
                        </a>
                    </h3>
                    <h4>Topic: <span
                                title="<?php echo $post->getExtensionAttributes()
                                    ->getTopicDescription(); ?>"><?php echo $post->getExtensionAttributes()
                                ->getTopicName(); ?></span></h4>
                    <p class="post-date">
                        <?php echo $post->getCreationTime(); ?>
                        <a href="<?php echo $block->getUrl(
                            'blog/index/delete',
                            [InstallSchema::ID_FIELD_NAME => $post->getId()]
                        ); ?>">delete?</a>
                    </p>
                    <p>Last
                        Edit: <?php echo $post->getUpdatedTime(); ?> </p>
                    <p class="post-content"><?php echo $post->getContent(); ?></p>
                </div>
            <?php endforeach; ?>
        <?php endif; ?>
    </div>
</div>