<?php
/**
 * Customer list view template.
 *
 * @category   Ecommistry
 * @package    Ecommistry_Repository
 * @copyright  Copyright (c) 2018 ecommistry (http://www.ecommistry.com)
 * @license    http://framework.zend.com/license   BSD License
 * @version    Release: 1.0
 * @link       http://framework.zend.com/package/PackageName
 * @since      Class available since Release 1.0
 */

/** @var \Ecommistry\Repository\Block\ListCustomers $block */
/** @var \Ecommistry\Repository\Api\Data\CustomerInterface' $customer */

$countries = ['New Zealand', 'Japan', 'China', 'Russia'];
?>

<?php foreach ($countries as $country) : ?>
    <h3><?php echo $country; ?></h3>
    <?php $customers = $block->getCustomersByCountryName($country); ?>
    <ul>
        <?php foreach ($customers as $customer) : ?>
            <li>
                <p><?php echo $customer->getLastName() . ', '
                        . $customer->getFirstName(); ?></p>
                <p><?php echo $customer->getAddress() . ', '
                        . $customer->getCountry() ?></p>
            </li>
        <?php endforeach; ?>
    </ul>
<?php endforeach; ?>
