<?php
/**
 * Products List
 *
 * @category   Ecommistry
 * @package    Ecommistry_Blog
 * @copyright  Copyright (c) 2018 ecommistry (http://www.ecommistry.com)
 * @license    http://framework.zend.com/license   BSD License
 * @version    Release: 1.0
 * @link       http://framework.zend.com/package/PackageName
 * @since      Class available since Release 1.0
 */

/** @var \Ecommistry\Blog\Block\Products $block */

$collection = $block->getLoadedProductCollection();
?>

<?php if (!$collection) : ?>
    <div class="message info empty">
        <div><?= /* @escapeNotVerified */
            __('We can\'t find products matching the selection.') ?></div>
    </div>
<?php else : ?>
    <div class="blog-products-wrapper">
        <ul class="blog-products-list">
            <?php foreach ($collection as $product) : ?>
                <?php /** @var \Magento\Catalog\Api\Data\ProductInterface $product */ ?>
                <li class="blog-product"><a
                            href="<?php echo($product->getProductUrl()); ?>"><?php echo $product->getName(); ?></a>
                    Price: $<?php echo sprintf(
                        '%.2f',
                        $product->getFinalPrice()
                    ); ?>
                </li>
            
            <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>

