<?php
/**
 * Short description for file
 *
 * Long description for file (if any)...
 *
 * @category   Zend
 * @package    Zend_Masterng
 * @subpackage SampleModule
 * @copyright  Copyright (c) 2018 ecommistry (http://www.ecommistry.com)
 * @license    http://framework.zend.com/license   BSD License
 * @version    Release: 1.0
 * @link       http://framework.zend.com/package/PackageName
 * @since      Class available since Release 1.0
 */

namespace Mastering\SampleModule\view\frontend\templates;

/** @var \Mastering\SampleModule\Block\Hello $block */
?>

<?php foreach ($block->getItems() as $item) : ?>
    <p><?php echo $item->getName(); ?>
        : <?php echo $item->getDescription(); ?></p>
<?php endforeach; ?>
